### ISSUE TITLE
Getting 'url' is not a valid tag or filter in tag library 'future' error on add slider item page

### ISSUE THREAD

**Issue by senoadiw** [bitmazk/django-hero-slider#5]
Greetings,

The error breaks Django Hero Slider on Django 1.9 and beyond since {% load url from future %} is deprecated.

Regards,

SN

**Comment by Tyrdall** [comment]
Thanks @senoadiw. Fixed in https://github.com/bitmazk/django-hero-slider/commit/1c88d9fa978f52be238edb445d870aaea933ba5b
